### ISSUE TITLE
push messages not working asynchronously

### ISSUE THREAD

**Issue by tony--** [appMobiGithub/sample-appmobi-privatestack#14]
I'm not sure if this is an issue with the sample code or with [the plugin](https://github.com/appMobiGithub/cordova-plugin-appmobi).

Also not sure if this issue affects PrivateStack or only Shared Cloud users.

After correctly setting up the sample for push, building and installing on device, I am able to add a push user (I can see in my admin console that I have 1 subscriber).  However, I cannot receive push messages when the app is stopped.

According to @mr5080 who was also testing this, the problem is actually a bit worse: the only time push messages are received are when the app is restarted.

Hopefully this will be enough info to allow you to reproduce the problem; if not I will provide more detailed steps.

**Comment by bwebsterdv** [comment]
I was having some issues this afternoon as well, but now in testing tonight I have seen no problems.  I was able to (almost instantly) receive push notifications for a new application created on the public cloud, with the sample bundle codebase.  I tested with app open, in background, and closed multiple times this evening with no issues.  However, this afternoon I was not always getting my push notifications.  Can you detail out the build, device, etc?  Thanks!
