### ISSUE TITLE
the CLI version overrides should be removed

### ISSUE THREAD

**Issue by tony--** [appMobiGithub/sample-appmobi-privatestack#15]
These lines were for integration testing only and should not have been added to the sample.
`<!-- -iOS --><intelxdk:cordova-cli version="5.1.1"/>`
`<!-- +iOS --><intelxdk:cordova-cli version="5.4.1"/>`

If they are present when the new XDK is released, they will cause a build error.

**Comment by inderpreet-singh** [comment]
We have removed the cordova-ios CLI overrides

**Comment by tony--** [comment]
Ok, closing.
