### ISSUE TITLE
update README.md

### ISSUE THREAD

**Issue by tony--** [appMobiGithub/sample-appmobi-privatestack#2]
Currently README.md only has some boilerplate info and should be updated with more information.
One possible reference is the Intel XDK "Hello, Cordova" sample:
https://github.com/gomobile/sample-hello-cordova

This sample README might be a good place to include information about what platforms are currently supported in conjunction with the Intel XDK (e.g., if initially only Android will work this would be a good place to call it out, then as the list of supported platforms changes, the README can be updated, a new version of the sample can be released and the Intel XDK feed can be updated).

**Comment by prabhjot87** [comment]
Thanks for the feedback. We have updated README.md file.

**Comment by tony--** [comment]
Looks pretty good to me!  Suggested edit:
iOS (For Intel XDK the plugin will not work for iOS as it has dependency on cordova v4.0.0 which has not been released yet.)
-->
iOS (For Intel XDK the plugin will not work for iOS as it has dependency on cordova-ios v4.0.0 which has not been released yet.)

**Comment by inderpreet-singh** [comment]
We have updated the Readme.md file with the mentioned suggestion (**cordova** -> **cordova-ios**)

**Comment by tony--** [comment]
Thanks!
