### ISSUE TITLE
update sample for consistency with "Hello, Cordova" sample

### ISSUE THREAD

**Issue by tony--** [appMobiGithub/sample-appmobi-privatestack#3]
Previously the Cordova Blank Template was provided as the reference Intel XDK app.
Please refer to this one instead, which is more up to date and is a sample instead of a template:
https://github.com/gomobile/sample-hello-cordova

In particular, review the app.json and hello-cordova.xdk files:
https://github.com/gomobile/sample-hello-cordova/blob/master/app.json
https://github.com/gomobile/sample-hello-cordova/blob/master/hello-cordova.xdk

**Comment by tony--** [comment]
Mentioning @xmnboy for input/awareness.

**Comment by IntelAnushaM** [comment]
The icon.png file needs to be resized to [72px x 72px] and screenshot.png should be exactly of resolution 226x413 if possible.

**Comment by IntelAnushaM** [comment]
The Intel XDK samples typically include a License file: [https://github.com/gomobile/sample-hello-cordova/blob/master/LICENSE.md](https://github.com/gomobile/sample-hello-cordova/blob/master/LICENSE.md)

You might want to include one too. Or you can use the one above for reference. Thanks!

**Comment by prabhjot87** [comment]
Thanks for the feedback. We have updated icon and screenshot.

**Comment by bwebsterdv** [comment]
Updated the project files from India, is this structure look okay?

**Comment by tony--** [comment]
All of the items identified in this issue have been addressed at this point - closing.
