### ISSUE TITLE
Make the link in description be a link

### ISSUE THREAD

**Issue by tony--** [appMobiGithub/sample-appmobi-privatestack#6]
You should just need to surround the link in app.json:description with an <a> tag.

**Comment by tony--** [comment]
Actually due to a limitation in the current release of Intel XDK, we should just use text (links will open in the client window instead of an external browser).
Maybe instead of actually putting the URL into the description (it's not selectable, so users cannot copy/paste), it would be better to say something like
"Using this sample requires a free Appmobi license.  Visit the README for this sample to learn how to sign up."

**Comment by bwebsterdv** [comment]
Updated description with that format, thanks!
