### ISSUE TITLE
Add/improve instructions in README related to plugin parameters

### ISSUE THREAD

**Issue by tony--** [appMobiGithub/sample-appmobi-privatestack#7]
When the user creates a new app based on the sample in Intel XDK, the Appmobi plugin will be added using the default parameter values.
Before the user builds the app, they need to edit these values using the plugin manager in the XDK.
This should be clearly called out in the README.

**Comment by prabhjot87** [comment]
Thanks for the feedback.

We have updated the README.md by adding the required lines.

**Comment by tony--** [comment]
Thanks
