### ISSUE TITLE
Configure sample for specific version of Appmobi plugin

### ISSUE THREAD

**Issue by tony--** [appMobiGithub/sample-appmobi-privatestack#8]
Currently the sample is configured with the sample-specific value of '?' for the version of the Appmobi plugin (this was probably done by the scripts that @anushamuts provided, which are working as intended, but when specific versions are required (as is the case here) they must be manually reset).  I think that this will result in HEAD of the master branch being added - this might include dev changes or untested code.

The sample should be configured to depend on a specific value in order to ensure stability.
Currently I think the value is 1.0.2, but maintaining the version in the sample will require ongoing maintenance.

**Comment by prabhjot87** [comment]
@tony-- Thanks for the feedback.

We tried to test this case with following scenario:

1) We modified version in appmobi plugin from "?" to 1.0.0 in our XDK file locally. The branch 1.0.0 exists in our plugin. We then imported modified template with updated version in Intel XDK and found that the plugin installed is 1.0.1 instead of 1.0.0.

2) We also tested the same by manually adding the plugin from https://github.com/appMobiGithub/cordova-plugin-appmobi.git#1.0.0 using "Plugin Management" option and it work as intended i.e 1.0.0.

We just wanted your feedback in point #1 that adding a specific version in .xdk file is intended to install from a specific branch but in our case it just installs latest branch which is 1.0.1.

Please let us know if we are missing something.

Thanks

**Comment by tony--** [comment]
@prabhjot87 Sounds like a bug - I'll try to reproduce and get back to you with a workaround (if possible) ASAP.

**Comment by tony--** [comment]
@prabhjot87 - In the case where "?" is specified, the XDK should use the default version specified in the XDK plugin feed.  When the sample specifies the version, that version should be used by the XDK.  Can you give me complete steps for how to reproduce the issue that you describe?  Specifically, I'm not sure about 2 things.  
1. what are the edits you made to specify 1.0.0
2. what steps you took to import the modified template.

**Comment by tony--** [comment]
@prabhjot87 - It seems that version might not be used when the plugin has originType "repo".  Instead, the gitref can be used to control what version will be retrieved.  However, it seems that even when the gitref is specified, the XDK silently switches to the version specified in the PLUGIN feed.  In order to test this, I added the appmobi plugin as a third-party plugin, specifying a gitref of v1.0.0.  The XDK reported that v1.0.0 of the plugin had been added, but when i checked the .xdk file in my project, the version and gitref had been changed to v1.0.1.  
This seems like a bug - I will need to check with others on my team.  

In any case, the solution (or at least workaround) is to make sure that the feed has been updated to have the version that the sample is configured to use.  For example, if you were to publish a "v1.0.2" version of the plugin, then the updates would be:
1. on github, publish a new version of plugin (tag the correct commit as "v1.0.2")
2. on github, update sample .xdk file to use new version of the plugin (change the gitref field to "v1.0.2", the version field can be "?")
3. in XDK feed management system (no externally accessible), update the feed to include "v1.0.2" as the latest version

**Comment by anushamuts** [comment]
@tony-- I am able to reproduce the issue @prabhjot87 is talking about. 

This is the workaround I found with Paul - remove the "?" in the version and leave it null - "". Change gitref to 'v1.0.0' which is the tag name in your appmobi plugin git repo. This fetches version 1.0.0.

Changes to be made:
"version": "",
"gitref": "v1.0.0",

**Comment by prabhjot87** [comment]
@tony @anushamuts - Thanks for the update.

The changes suggested by @anushamuts  work for us and we have pushed the changes to Github.

**Comment by tony--** [comment]
Thanks, closing.
