### ISSUE TITLE
update sample to depend on cordova-plugin-inappbrowser 1.1.1 when it is released

### ISSUE THREAD

**Issue by tony--** [appMobiGithub/sample-appmobi-privatestack#9]
This issue cannot be addressed until cordova-plugin-inappbrowser 1.1.1 is released - the release vote is underway now and barring any issues, it should pass today.

This release will include a fix for [CB-10040](https://issues.apache.org/jira/browse/CB-10040), which is the blocker bug that caused the Appmobi plugin to depend on a fork of cordova-plugin-inappbrowser.

Refer to https://issues.apache.org/jira/browse/CB-10187 for more information.

**Comment by tony--** [comment]
[cordova-plugin-inappbrowser 1.1.1 has been released](https://www.npmjs.com/package/cordova-plugin-inappbrowser), so this issue can be resolved now.

**Comment by inderpreet-singh** [comment]
Thanks for the update, we have updated our plugin dependency to use the latest release 1.1.1 of InAppBrowser plugin

**Comment by tony--** [comment]
In order to make sample depend on cordova-plugin-inappbrowser, the [plugin dependency version](https://github.com/appMobiGithub/sample-appmobi-privatestack/blob/master/sample-appmobi-privatestack.xdk#L71) must be updated in the .xdk file.
I'll submit a PR for this.
